version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: ./compose/odoo/Dockerfile
    image: docker_odoo_data
    container_name: docker_odoo_data
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - '8879:8069'
      - '8888:3001'
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
  db: 
    image: postgres:14.6
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
  
